sudo: required

language: python

python:
  - "3.4"

services:
  - docker

before_install:
  - docker build -t test_snakes .
  - docker run --rm -p8080:80 test_snakes
  - pip install -r tests/requirements.txt

script:
  - pytest tests
